update dockerfile

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -32,12 +32,14 @@ jobs:
       run: |
         echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy_key.pem
         chmod 600 deploy_key.pem
-        scp -o StrictHostKeyChecking=no -i deploy_key.pem build.tar.gz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/tmp/build.tar.gz
+        scp -o StrictHostKeyChecking=no -i deploy_key.pem docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/sporting-event-pwa/docker-compose.yml
         ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
           set -e  # Stop the script if any command fails
-          sudo mv /tmp/build.tar.gz /sporting-event-pwa/build.tar.gz
           cd /sporting-event-pwa
-          sudo tar -xzf build.tar.gz
+          if [ ! -f docker-compose.yml ]; then
+            echo "Docker-compose configuration file not found"
+            exit 1
+          fi
           docker-compose pull
           docker-compose up -d
         EOF
