update dockerfile

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -27,4 +27,18 @@ jobs:
       run: |
         docker-compose -f docker-compose.yml build
         docker-compose -f docker-compose.yml push
-        
+      
+    - name: Deploy to Server
+      run: |
+        echo "${{ secrets.SSH_DEPLOY_KEY }}" > deploy_key.pem
+        chmod 600 deploy_key.pem
+        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
+          set -e  # Stop the script if any command fails
+          mkdir -p /sport-event-pwa  # Create the directory if it does not exist
+          cd /sport-event-pwa
+          docker-compose pull
+          docker-compose up -d
+        EOF
+      shell: bash
+      cleanup: 
+        run: rm -f deploy_key.pem
